 sytrading --username shang0001@gmail.com/SYTradingPublicSite/Controllers/GloveController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SYTradingPublicSite.Models;
using SYTradingPublicSite.ViewModels;

namespace SYTradingPublicSite.Controllers
{
    public class GloveController : Controller
    {
        private businessDbEntities db = new businessDbEntities();

        private string StorageRoot
        {
            get { return Path.Combine(Path.GetDirectoryName(Path.GetDirectoryName(Server.MapPath("~"))), "Gloves/"); }
        }

        [HttpGet]
        public void Download(string id, bool thumbnail = false)
        {
            var filename = id;
            var filePath = thumbnail ? Path.Combine(StorageRoot, "thumbnails/" + filename) : Path.Combine(StorageRoot, filename);

            var context = HttpContext;

            if (System.IO.File.Exists(filePath))
            {
                context.Response.AddHeader("Content-Disposition", "attachment; filename=\"" + filename + "\"");
                context.Response.ContentType = "application/octet-stream";
                context.Response.ClearContent();
                context.Response.WriteFile(filePath);
            }
            else
                context.Response.StatusCode = 404;
        }

        //
        // GET: /Glove/
        [OutputCache(CacheProfile = "CacheGlove", VaryByParam = "selectedApplicationCategory;materialID", NoStore = true)]
        public ActionResult Index(string selectedApplicationCategory, string materialID)
        {
            GloveViewModel model = this.InitializeNavData();

            if (string.IsNullOrEmpty(selectedApplicationCategory) && string.IsNullOrEmpty(materialID))
            {
                selectedApplicationCategory = db.Applications.First().Category;
            }

            if (!string.IsNullOrEmpty(selectedApplicationCategory))
            {
                int[] selectedGloveIDs = db.Applications.Include(a => a.GloveApplications)
                    .Where(a => a.Category == selectedApplicationCategory)
                    .SelectMany(a => a.GloveApplications)
                    .GroupBy(ga => ga.GloveID)
                    .Select(ga => ga.Key).ToArray();

                foreach (int id in selectedGloveIDs)
                {
                    if (db.Gloves.Where(g => g.GloveID == id && g.Released == true).Count() > 0)
                    {
                        model.Gloves.Add(db.Gloves.Where(g => g.GloveID == id && g.Released == true).Single());
                    }
                }
                model.selectedApplicationCategory = selectedApplicationCategory;
            }
            else
            {
                int mid = int.Parse(materialID);
                if (db.Gloves.Where(g => g.MaterialID == mid && g.Released == true).Count() > 0)
                {
                    model.Gloves.AddRange(db.Gloves.Where(g => g.MaterialID == mid && g.Released == true));
                }
                model.selectedMaterialID = mid;
            }
            
            return View(model);
        }

        //
        // GET: /Glove/Details/5
        [OutputCache(CacheProfile = "CacheGlove", VaryByParam = "id", NoStore = true)]
        public ActionResult Details(int id = 0)
        {
            GloveViewModel model = this.InitializeNavData();

            Glove glove = db.Gloves
                            .Include(g => g.ImagePaths)
                            .Include(g => g.GloveApplications)
                            .Where(g => g.GloveID == id)
                            .Single();

            if (glove == null)
            {
                return HttpNotFound();
            }

            model.Gloves.Add(glove);

            string selectedApplicationCategory = Request.Params["selectedApplicationCategory"];
            string materialID = Request.Params["selectedMaterialID"];

            if (!string.IsNullOrEmpty(selectedApplicationCategory))
            {
                int[] selectedGloveIDs = db.Applications.Include(a => a.GloveApplications)
                    .Where(a => a.Category == selectedApplicationCategory)
                    .SelectMany(a => a.GloveApplications)
                    .GroupBy(ga => ga.GloveID)
                    .Select(ga => ga.Key).ToArray();

                foreach (int gid in selectedGloveIDs)
                {
                    if (db.Gloves.Where(g => g.GloveID != id && g.GloveID == gid && g.Released == true).Count() > 0)
                    {
                        model.RelatedGloves.Add(db.Gloves.Where(g => g.GloveID != id && g.GloveID == gid && g.Released == true).Single());
                    }
                }
                model.selectedApplicationCategory = selectedApplicationCategory;
            }
            else
            {
                int mid = int.Parse(materialID);
                if (db.Gloves.Where(g => g.GloveID != id && g.MaterialID == mid && g.Released == true).Count() > 0)
                {
                    model.RelatedGloves.AddRange(db.Gloves.Where(g => g.GloveID != id && g.MaterialID == mid && g.Released == true));
                }
                model.selectedMaterialID = mid;
            }





            //foreach (GloveApplication gloveApplication in glove.GloveApplications)
            //{
            //    var anotherGAs = gloveApplication.Application.GloveApplications.Where(ga => ga.GloveApplicationID != gloveApplication.GloveApplicationID);

            //    if (anotherGAs.Count() == 0)
            //    {
            //        break;
            //    }

            //    Glove relatedGlove = db.Gloves.Find(anotherGAs.Where(g => g.Glove.Released == true).First().GloveID);

            //    if (!model.RelatedGloves.Contains(relatedGlove) && relatedGlove.ImagePaths.Count > 0)
            //    {
            //        model.RelatedGloves.Add(relatedGlove);
            //        model.ImageThumbnailPath.Add(relatedGlove.GloveID, relatedGlove.ImagePaths.First().Path + "?thumbnail=true");

            //        if (model.RelatedGloves.Count == 5)
            //        {
            //            break;
            //        }
            //    }
            //}

            return View(model);
        }

        public string ClearCache(int? id, bool? clearIndexOnly)
        {
            HttpResponse.RemoveOutputCacheItem("/Glove");

            if (id.HasValue)
            {
                HttpResponse.RemoveOutputCacheItem(string.Format("/Glove/Details/{0}", id));
            }
            else if (!(clearIndexOnly.HasValue && clearIndexOnly.Value == true))
            {
                foreach (var gid in db.Gloves.Select(g => g.GloveID))
                {
                    HttpResponse.RemoveOutputCacheItem(string.Format("/Glove/Details/{0}", gid));
                }
            }

            return "Clear!";
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        private GloveViewModel InitializeNavData()
        {
            GloveViewModel model = new GloveViewModel();
            model.Gloves = new List<Glove>();
            model.RelatedGloves = new List<Glove>();

            model.ApplicationCategories = db.Applications.GroupBy(a => a.Category).Select(lst => lst.Key).ToArray();
            model.Materials = db.Materials.ToArray();

            return model;
        }
    }
}

 sytrading --username shang0001@gmail.com/SYTradingPublicSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using SYTradingPublicSite.Models;
using SYTradingPublicSite.ViewModels;

namespace SYTradingPublicSite.Controllers
{
    public class HomeController : Controller
    {
        private businessDbEntities db = new businessDbEntities();

        private string StorageRoot
        {
            get { return Path.Combine(Server.MapPath("~/Images/banner/Home/")); }
        }

        [HttpGet]
        public void Download(string id)
        {
            var filename = id;
            var filePath = Path.Combine(StorageRoot, filename);

            var context = HttpContext;

            if (System.IO.File.Exists(filePath))
            {
                context.Response.AddHeader("Content-Disposition", "attachment; filename=\"" + filename + "\"");
                context.Response.ContentType = "application/octet-stream";
                context.Response.ClearContent();
                context.Response.WriteFile(filePath);
            }
            else
                context.Response.StatusCode = 404;
        }

        [OutputCache(CacheProfile = "CacheHome", VaryByParam = "none", NoStore = true)]
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";
            ViewBag.BannerImages = Directory.EnumerateFiles(this.StorageRoot)
                                        .Select(p => Path.GetFileName(p)).OrderBy(p => Path.GetFileName(p)).ToArray();

            return View();
        }

        [OutputCache(CacheProfile = "CacheHome", VaryByParam = "none", NoStore = true)]
        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        [OutputCache(CacheProfile = "CacheHome", VaryByParam = "none", NoStore = true)]
        public ActionResult Contact()
        {
            ViewBag.Message = "SHANGYUE TRADING LIMITED";
            ViewBag.Create = true;

            var viewModel = new HomeViewModel();
            viewModel.Titles = new SelectList(new string[] { "Mr.", "Ms.", "Mrs.", "Miss" });
            viewModel.Countries = new SelectList(new string[] { string.Empty,
"UNITED STATES",
"CANADA",
"AFGHANISTAN",
"ÅLAND ISLANDS",
"ALBANIA",
"ALGERIA",
"AMERICAN SAMOA",
"ANDORRA",
"ANGOLA",
"ANGUILLA",
"ANTARCTICA",
"ANTIGUA AND BARBUDA",
"ARGENTINA",
"ARMENIA",
"ARUBA",
"AUSTRALIA",
"AUSTRIA",
"AZERBAIJAN",
"BAHAMAS",
"BAHRAIN",
"BANGLADESH",
"BARBADOS",
"BELARUS",
"BELGIUM",
"BELIZE",
"BENIN",
"BERMUDA",
"BHUTAN",
"BOLIVIA, PLURINATIONAL STATE OF",
"BONAIRE, SINT EUSTATIUS AND SABA",
"BOSNIA AND HERZEGOVINA",
"BOTSWANA",
"BOUVET ISLAND",
"BRAZIL",
"BRITISH INDIAN OCEAN TERRITORY",
"BRUNEI DARUSSALAM",
"BULGARIA",
"BURKINA FASO",
"BURUNDI",
"CAMBODIA",
"CAMEROON",
"CAPE VERDE",
"CAYMAN ISLANDS",
"CENTRAL AFRICAN REPUBLIC",
"CHAD",
"CHILE",
"CHINA",
"CHRISTMAS ISLAND",
"COCOS (KEELING) ISLANDS",
"COLOMBIA",
"COMOROS",
"CONGO",
"CONGO, THE DEMOCRATIC REPUBLIC OF THE",
"COOK ISLANDS",
"COSTA RICA",
"CÔTE D'IVOIRE",
"CROATIA",
"CUBA",
"CURAÇAO",
"CYPRUS",
"CZECH REPUBLIC",
"DENMARK",
"DJIBOUTI",
"DOMINICA",
"DOMINICAN REPUBLIC",
"ECUADOR",
"EGYPT",
"EL SALVADOR",
"EQUATORIAL GUINEA",
"ERITREA",
"ESTONIA",
"ETHIOPIA",
"FALKLAND ISLANDS (MALVINAS)",
"FAROE ISLANDS",
"FIJI",
"FINLAND",
"FRANCE",
"FRENCH GUIANA",
"FRENCH POLYNESIA",
"FRENCH SOUTHERN TERRITORIES",
"GABON",
"GAMBIA",
"GEORGIA",
"GERMANY",
"GHANA",
"GIBRALTAR",
"GREECE",
"GREENLAND",
"GRENADA",
"GUADELOUPE",
"GUAM",
"GUATEMALA",
"GUERNSEY",
"GUINEA",
"GUINEA-BISSAU",
"GUYANA",
"HAITI",
"HEARD ISLAND AND MCDONALD ISLANDS",
"HOLY SEE (VATICAN CITY STATE)",
"HONDURAS",
"HONG KONG",
"HUNGARY",
"ICELAND",
"INDIA",
"INDONESIA",
"IRAN, ISLAMIC REPUBLIC OF",
"IRAQ",
"IRELAND",
"ISLE OF MAN",
"ISRAEL",
"ITALY",
"JAMAICA",
"JAPAN",
"JERSEY",
"JORDAN",
"KAZAKHSTAN",
"KENYA",
"KIRIBATI",
"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
"KOREA, REPUBLIC OF",
"KUWAIT",
"KYRGYZSTAN",
"LAO PEOPLE'S DEMOCRATIC REPUBLIC",
"LATVIA",
"LEBANON",
"LESOTHO",
"LIBERIA",
"LIBYA",
"LIECHTENSTEIN",
"LITHUANIA",
"LUXEMBOURG",
"MACAO",
"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
"MADAGASCAR",
"MALAWI",
"MALAYSIA",
"MALDIVES",
"MALI",
"MALTA",
"MARSHALL ISLANDS",
"MARTINIQUE",
"MAURITANIA",
"MAURITIUS",
"MAYOTTE",
"MEXICO",
"MICRONESIA, FEDERATED STATES OF",
"MOLDOVA, REPUBLIC OF",
"MONACO",
"MONGOLIA",
"MONTENEGRO",
"MONTSERRAT",
"MOROCCO",
"MOZAMBIQUE",
"MYANMAR",
"NAMIBIA",
"NAURU",
"NEPAL",
"NETHERLANDS",
"NEW CALEDONIA",
"NEW ZEALAND",
"NICARAGUA",
"NIGER",
"NIGERIA",
"NIUE",
"NORFOLK ISLAND",
"NORTHERN MARIANA ISLANDS",
"NORWAY",
"OMAN",
"PAKISTAN",
"PALAU",
"PALESTINE, STATE OF",
"PANAMA",
"PAPUA NEW GUINEA",
"PARAGUAY",
"PERU",
"PHILIPPINES",
"PITCAIRN",
"POLAND",
"PORTUGAL",
"PUERTO RICO",
"QATAR",
"RÉUNION",
"ROMANIA",
"RUSSIAN FEDERATION",
"RWANDA",
"SAINT BARTHÉLEMY",
"SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
"SAINT KITTS AND NEVIS",
"SAINT LUCIA",
"SAINT MARTIN (FRENCH PART)",
"SAINT PIERRE AND MIQUELON",
"SAINT VINCENT AND THE GRENADINES",
"SAMOA",
"SAN MARINO",
"SAO TOME AND PRINCIPE",
"SAUDI ARABIA",
"SENEGAL",
"SERBIA",
"SEYCHELLES",
"SIERRA LEONE",
"SINGAPORE",
"SINT MAARTEN (DUTCH PART)",
"SLOVAKIA",
"SLOVENIA",
"SOLOMON ISLANDS",
"SOMALIA",
"SOUTH AFRICA",
"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
"SOUTH SUDAN",
"SPAIN",
"SRI LANKA",
"SUDAN",
"SURINAME",
"SVALBARD AND JAN MAYEN",
"SWAZILAND",
"SWEDEN",
"SWITZERLAND",
"SYRIAN ARAB REPUBLIC",
"TAIWAN, PROVINCE OF CHINA",
"TAJIKISTAN",
"TANZANIA, UNITED REPUBLIC OF",
"THAILAND",
"TIMOR-LESTE",
"TOGO",
"TOKELAU",
"TONGA",
"TRINIDAD AND TOBAGO",
"TUNISIA",
"TURKEY",
"TURKMENISTAN",
"TURKS AND CAICOS ISLANDS",
"TUVALU",
"UGANDA",
"UKRAINE",
"UNITED ARAB EMIRATES",
"UNITED KINGDOM",
"UNITED STATES MINOR OUTLYING ISLANDS",
"URUGUAY",
"UZBEKISTAN",
"VANUATU",
"VENEZUELA, BOLIVARIAN REPUBLIC OF",
"VIET NAM",
"VIRGIN ISLANDS, BRITISH",
"VIRGIN ISLANDS, U.S.",
"WALLIS AND FUTUNA",
"WESTERN SAHARA",
"YEMEN",
"ZAMBIA",
"ZIMBABWE"
            });

            return View(viewModel);
        }

        //
        // POST: /Customer/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Contact(HomeViewModel model)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(model.Customer);
                db.SaveChanges();

                if (!string.IsNullOrEmpty(model.Message.Subject) || !string.IsNullOrEmpty(model.Message.Body))
                {
                    model.Message.CustomerID = model.Customer.CustomerID;
                    db.Messages.Add(model.Message);
                    db.SaveChanges();
                }

                ViewBag.Create = false;

                if (!string.IsNullOrEmpty(model.Message.Subject) || !string.IsNullOrEmpty(model.Message.Body))
                {
                    SendEmail(model.Customer.Email, (model.Customer.FirstName + " "  + model.Customer.LastName), model.Message.Subject, model.Message.Body);
                }
            }

            return View();
        }

        public string ClearCache()
        {
            HttpResponse.RemoveOutputCacheItem("/");
            HttpResponse.RemoveOutputCacheItem("/Home");
            HttpResponse.RemoveOutputCacheItem("/Home/Index");
            HttpResponse.RemoveOutputCacheItem("/Home/About");
            HttpResponse.RemoveOutputCacheItem("/Home/Contact");
            return "Clear!";
        }

        private void SendEmail(string sender, string displayName, string subject, string body)
        {
            try
            {
                Dictionary<string, string> dictionary =
                    db.Configs.Where(c => c.Enabled == true).ToDictionary(p => p.Name, c => c.Value);

                MailMessage mailMsg = new MailMessage();
                if (dictionary.ContainsKey("admin_email"))
                {
                    mailMsg.To.Add(dictionary["admin_email"]);
                }
                else
                {
                    throw new KeyNotFoundException("Email settings key \"admin_email\" is not found, please check immediately!");
                }

                // From
                MailAddress mailAddress = new MailAddress(dictionary["smtp_server_username"]);
                mailMsg.From = mailAddress;

                // Subject and Body
                mailMsg.Subject = "New inquery";
                mailMsg.Body = string.Format(
                    "There is a new inquery to Shang Yue Trading Ltd:\n\n Customer: {0}\n Email: {1}\n Subject:{2}\n Body:{3}",
                    displayName,
                    sender,
                    subject,
                    body);
                //mailMsg.IsBodyHtml = true;

                SmtpClient smtpClient = null;
                // Init SmtpClient and send on port 587 in my case. (Usual=port25)
                if (dictionary.ContainsKey("smtp_server") && dictionary.ContainsKey("smtp_server_port"))
                {
                    smtpClient = new SmtpClient(
                        dictionary["smtp_server"],
                        int.Parse(dictionary["smtp_server_port"]));
                }
                else
                {
                    throw new KeyNotFoundException("Email settings key \"smtp_server\" or \"smtp_server_port\" is not found, please check immediately!");
                }


 sytrading --username shang0001@gmail.com/SYTradingPublicSite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span6">
            <h1>@ViewBag.Title.</h1>
            <h2>@ViewBag.Message</h2>
            </hgroup>
            <article>
                <p>
                    About our company
                </p>
            </article>
        </div>
        <div class="span6">
        </div>
    </div>
</div>

 sytrading --username shang0001@gmail.com/SYTradingPublicSite/Views/Home/Contact.cshtml
@model SYTradingPublicSite.ViewModels.HomeViewModel

@{
    ViewBag.Title = "Contact Us";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span4">
            <hgroup class="title">
                <h2>@ViewBag.Message</h2>
            </hgroup>

            <section class="contact">
                <header>
                    <h3>Phone</h3>
                </header>
                <p>
                    <span class="label">Main:</span>
                    <span>00852-28113180</span>
                </p>
                <p>
                    <span class="label">After Hours:</span>
                    <span>00852-28113620</span>
                </p>
            </section>

            <section class="contact">
                <header>
                    <h3>Email</h3>
                </header>
                <p>
                    <span class="label">Marketing:</span>
                    <span><a href="mailto:marketing@shangyuetrading.com">marketing@shangyuetrading.com</a></span>
                </p>
            </section>

            <section class="contact">
                <header>
                    <h3>Address</h3>
                </header>
                <p>
                    UNIT 905, WORKINGBERG COMMERCIAL BUILDING<br />
                    41-47 MARBLE ROAD<br />
                    HONG KONG
                </p>
            </section>
        </div>
        <div class="span8">
            @if (ViewBag.Create)
            {
                <h2>Leave us your message</h2>

                using (Html.BeginForm())
                {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <div class="row-fluid">
                    <div class="span5">
                        <fieldset>
                            <legend>Your information:</legend>

                            <div class="editor-label">
                                @Html.LabelFor(model => model.Customer.Title)
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(model => model.Customer.Title, Model.Titles)
                                @Html.ValidationMessageFor(model => model.Customer.Title)
                            </div>

                            <div class="editor-label">
                                @Html.LabelFor(model => model.Customer.FirstName)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.Customer.FirstName) <span style="color:red">*</span>
                                @Html.ValidationMessageFor(model => model.Customer.FirstName)
                            </div>

                            <div class="editor-label">
                                @Html.LabelFor(model => model.Customer.LastName)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.Customer.LastName) <span style="color:red">*</span>
                                @Html.ValidationMessageFor(model => model.Customer.LastName)
                            </div>

                            <div class="editor-label">
                                @Html.LabelFor(model => model.Customer.Email)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.Customer.Email) <span style="color:red">*</span>
                                @Html.ValidationMessageFor(model => model.Customer.Email)
                            </div>

                            <div class="accordion" id="accordion2">
                                <div class="accordion-group">
                                    <div class="accordion-heading">
                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">Add my address also
                                        </a>
                                    </div>
                                    <div id="collapseOne" class="accordion-body collapse out">
                                        <div class="accordion-inner">
                                            <div class="editor-label">
                                                @Html.LabelFor(model => model.Customer.Phone)
                                            </div>
                                            <div class="editor-field">
                                                @Html.EditorFor(model => model.Customer.Phone)
                                                @Html.ValidationMessageFor(model => model.Customer.Phone)
                                            </div>

                                            <div class="editor-label">
                                                @Html.LabelFor(model => model.Customer.Fax)
                                            </div>
                                            <div class="editor-field">
                                                @Html.EditorFor(model => model.Customer.Fax)
                                                @Html.ValidationMessageFor(model => model.Customer.Fax)
                                            </div>

                                            <div class="editor-label">
                                                @Html.LabelFor(model => model.Customer.CompanyName)
                                            </div>
                                            <div class="editor-field">
                                                @Html.EditorFor(model => model.Customer.CompanyName)
                                                @Html.ValidationMessageFor(model => model.Customer.CompanyName)
                                            </div>

                                            <div class="editor-label">
                                                @Html.LabelFor(model => model.Customer.Address)
                                            </div>
                                            <div class="editor-field">
                                                @Html.EditorFor(model => model.Customer.Address)
                                                @Html.ValidationMessageFor(model => model.Customer.Address)
                                            </div>

                                            <div class="editor-label">
                                                @Html.LabelFor(model => model.Customer.City)
                                            </div>
                                            <div class="editor-field">
                                                @Html.EditorFor(model => model.Customer.City)
                                                @Html.ValidationMessageFor(model => model.Customer.City)
                                            </div>

                                            <div class="editor-label">
                                                @Html.LabelFor(model => model.Customer.Province)
                                            </div>
                                            <div class="editor-field">
                                                @Html.EditorFor(model => model.Customer.Province)
                                                @Html.ValidationMessageFor(model => model.Customer.Province)
                                            </div>

                                            <div class="editor-label">
                                                @Html.LabelFor(model => model.Customer.PostalCode)
                                            </div>
                                            <div class="editor-field">
                                                @Html.EditorFor(model => model.Customer.PostalCode)
                                                @Html.ValidationMessageFor(model => model.Customer.PostalCode)
                                            </div>

                                            <div class="editor-label">
                                                @Html.LabelFor(model => model.Customer.Country)
                                            </div>
                                            <div class="editor-field">
                                                @Html.DropDownListFor(model => model.Customer.Country, Model.Countries)
                                                @Html.ValidationMessageFor(model => model.Customer.Country)
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="editor-field">
                                @Html.EditorFor(model => model.Customer.NewsLetter)
                                @Html.ValidationMessageFor(model => model.Customer.NewsLetter)
                                I would like to receive the bi-weekly email news-letter that contains the latest product information and industry news.
                            </div>
                        </fieldset>
                    </div>
                    <div class="span7">
                         <fieldset>
                            <legend>Your inquery: </legend>
                            <div class="editor-label">
                                @Html.LabelFor(model => model.Message.Subject)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.Message.Subject)
                                @Html.ValidationMessageFor(model => model.Message.Subject)
                            </div>

                            <div class="editor-label">
                                @Html.LabelFor(model => model.Message.Body)
                            </div>
                            <div class="editor-field">
                                @Html.EditorFor(model => model.Message.Body)
                                @Html.ValidationMessageFor(model => model.Message.Body)
                            </div>
                        </fieldset>
                    </div>
                </div>
                            
                <p style="text-align:center">
                    <input class="btn" type="submit" value="Submit" />
                </p>
                }

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            }
            else
            {
                <h2>Thank you! Your message has been sent to us!</h2>
            }
        </div>
    </div>
</div>

 sytrading --username shang0001@gmail.com/SYTradingPublicSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="container home-page">
@*    <!-- Main hero unit for a primary marketing message or call to action -->
    <div class="hero-unit">
    </div>*@

    <!-- Example row of columns -->
    <div class="row home-icons">
        <div class="span12">
            <div class="flexslider">
                <ul class="slides">
                    @foreach (string filename in ViewBag.BannerImages)
                    {
                        <li>
                            <img src="@Url.Action("Download", new { id=filename })" />
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span8">
            Branding text here!
        </div>
        <div class="span4">
            <div style="display: inline-block">
            <h2>Gloves</h2>
            <p><a href="@Url.Action("Index", "Glove")">
                <img class="home-icon" src="~/Images/Gloves.png" /></a></p>
            </div>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div style="display: inline-block">
            <h2>Contact Us</h2>
            <p><a href="@Url.Action("Contact", "Home")">
                <img class="home-icon" src="~/Images/contact-us.png" /></a></p>
            </div>
        </div>
    </div>
</div>
<!-- /container -->
